### ISSUE TITLE
Error in kneaddata

### ISSUE THREAD

**Issue by Muneer111** [BioJulia/BiobakeryUtils.jl#109]
Hi @ EcoJulia
Hope you are fine and doing good
I am trying to run kneaddata and got this unexpected error

```
 **kneaddata –input1 /media/sf_Shared_folder/ovas/Final/81_R1.fastq --input2 /media/sf_Shared_folder/ovas/Final/81_R2.fastq --reference-db /home/qiime2/ref_dtabase/ --output kneaddata_81 --trimmomatic /home/qiime2/Trimmomatic-0.33
Reformatting file sequence identifiers …

Reformatting file sequence identifiers …

Reordering read identifiers …

Initial number of reads ( /home/qiime2/kneaddata_81/reordered_qhik9bbx_reformatted_identifierse3uxy95f_81_R1 ): 22625162.0
Initial number of reads ( /home/qiime2/kneaddata_81/reordered_enctz3x3_reformatted_identifiersd8ic66o3_81_R2 ): 22625162.0
Running Trimmomatic …
CRITICAL ERROR: Error executing: java -Xmx500m -jar /home/qiime2/Trimmomatic-0.33/trimmomatic-0.33.jar PE -threads 1 -phred33 /home/qiime2/kneaddata_81/reordered_qhik9bbx_reformatted_identifierse3uxy95f_81_R1 /home/qiime2/kneaddata_81/reordered_enctz3x3_reformatted_identifiersd8ic66o3_81_R2 /home/qiime2/kneaddata_81/81_R1_kneaddata.trimmed.1.fastq /home/qiime2/kneaddata_81/81_R1_kneaddata.trimmed.single.1.fastq /home/qiime2/kneaddata_81/81_R1_kneaddata.trimmed.2.fastq /home/qiime2/kneaddata_81/81_R1_kneaddata.trimmed.single.2.fastq MINLEN:60 ILLUMINACLIP:/home/qiime2/miniconda/envs/kneaddata/lib/python3.8/site-packages/kneaddata/adapters/NexteraPE-PE.fa:2:30:10:8:TRUE SLIDINGWINDOW:4:20 MINLEN:75

Error message returned from Trimmomatic :
<JAVA_HOME>/lib/ext exists, extensions mechanism no longer supported; Use -classpath instead.
.Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.**
```

kindly suggest further

**Comment by kescobo** [comment]
Hi @Muneer111 thanks for trying out the package!

This error is from `kneaddata` itself, rather than the wrapper provided by this package, so it needs to be fixed with the underlying installation. Did you install this with `BiobakeryUtils.install_deps()`, or some other way?

 I don't think I've ever seen this *specific* error before, but I've definitely seen problems with the `trimmomatic` dependency, [see eg here](https://forum.biobakery.org/t/kneaddata-installed-with-conda-is-not-available/4147/6)

**Comment by Muneer111** [comment]
Hi @kescobo 
thank you so much
No, I installed the kneaddata by this way
**$ conda create --name kneaddata
$ source activate kneaddata
$ conda install -c cyclus java-jre
$ conda install -c bioconda fastqc
$ conda install -c bioconda trf
$ conda install -c bioconda kneaddata
$ conda install pip
$ pip install kneaddata**
Then I installed Trimmomatic version 0.33 (but no through conda)
$ curl -o Trimmomatic-0.33.zip http://www.usadellab.org/cms/uploads/supplementary/Trimmomatic/Trimmomatic-0.33.zip
$ unzip Trimmomatic-0.33.zip
and finally installed the reference database
$ kneaddata_database --download human_genome bowtie2 <path/to/install/kneaddata_database.
And after successful installation ran the above mentioned command and resulted in error.
Thanks and Regards

**Comment by kescobo** [comment]
Hi @Muneer111 - So, that's a problem upstream of this package. I would recommend the following:

- If you are using this package to run `kneaddata()` from julia, try using `BiobakeryUtils.install_deps()`
- If you already have a `conda` environment, using `conda` to install trimmomatic
  - you may need to also set ` tbb=2020.2`, [see here](https://forum.biobakery.org/t/cant-get-metaphlan-to-complete-within-humann-3/1834/10?u=kescobo)

Note: this package is just a wrapper around biobakery, and not directly affiliated with them. If you have issues with biobakery command line functionality, please ask on their help forum https://forum.biobakery.org/

**Comment by Muneer111** [comment]
Hi @kescobo 
Thank you for your help. 
meanwhile I tried to download biobakery workflow
I followed this tutorial 
https://github.com/biobakery/biobakery_workflows/wiki/Installing-the-workflows-with-pip
and successfully installed biobakery_workflows_databases --install wmgx.
Now which tutorial I will follow to run my samples.
Thanks and Regards

**Comment by Muneer111** [comment]
Hi@ Kescobo
Hope you are fine and doing good.
Today I installed kneaddata and ran i sample, it started well but after few minutes gave error
**_Problem 1_**
**kneaddata --input1 /media/sf_Shared_folder/ovas/Final/81_R1.fastq --input2 /media/sf_Shared_folder/ovas/Final/81_R2.fastq --reference-db /home/qiime2/bowtie2/ --output kneadata_81 **
Reformatting file sequence identifiers …

Reformatting file sequence identifiers …

Reordering read identifiers …

Initial number of reads ( /home/qiime2/kneadata_81/reordered_7yj33gia_reformatted_identifiers7tpvjx6v_81_R1 ): 22625162.0
Initial number of reads ( /home/qiime2/kneadata_81/reordered_xxlw0fsb_reformatted_identifiersmuluit7e_81_R2 ): 22625162.0
**Running Trimmomatic … **
CRITICAL ERROR: Error executing: java -Xmx500m -jar /home/qiime2/miniconda/envs/kneaddata/bin/trimmomatic PE -threads 1 -phred33 /home/qiime2/kneadata_81/reordered_7yj33gia_reformatted_identifiers7tpvjx6v_81_R1 /home/qiime2/kneadata_81/reordered_xxlw0fsb_reformatted_identifiersmuluit7e_81_R2 /home/qiime2/kneadata_81/81_R1_kneaddata.trimmed.1.fastq /home/qiime2/kneadata_81/81_R1_kneaddata.trimmed.single.1.fastq /home/qiime2/kneadata_81/81_R1_kneaddata.trimmed.2.fastq /home/qiime2/kneadata_81/81_R1_kneaddata.trimmed.single.2.fastq MINLEN:60 ILLUMINACLIP:/home/qiime2/miniconda/envs/kneaddata/lib/python3.10/site-packages/kneaddata/adapters/NexteraPE-PE.fa:2:30:10:8:TRUE SLIDINGWINDOW:4:20 MINLEN:75

Error message returned from Trimmomatic :
java: symbol lookup error: java: undefined symbol: JLI_StringDup

**Problem 2**
I then tried to install biobakery_workflow_databses and got this error

biobakery_workflows_databases --install wmgx
Installing humann utility mapping database
Download URL: http://huttenhower.sph.harvard.edu/humann2_data/full_mapping_v201901.tar.gz
Downloading file of size: 2.55 GB

2.55 GB 100.00 % 1.49 MB/sec 0 min -0 sec
Extracting: /home/qiime2/biobakery_workflows_databases/humann/full_mapping_v201901.tar.gz

Database installed: /home/qiime2/biobakery_workflows_databases/humann/utility_mapping

HUMAnN configuration file updated: database_folders : utility_mapping = /home/qiime2/biobakery_workflows_databases/humann/utility_mapping
Generating strainphlan fasta database
Could not locate a Bowtie index corresponding to basename “/home/qiime2/miniconda/envs/kneaddata/lib/python3.8/site-packages/metaphlan/metaphlan_databases/mpa_v30_CHOCOPhlAn_201901”
Error: Encountered internal Bowtie 2 exception ([#1](https://github.com/timflutre/trimmomatic/issues/1))
Command: /home/qiime2/miniconda/envs/abmiguez kneaddata/bin/bowtie2-inspect-s --wrapper basic-0 /home/qiime2/miniconda/envs/kneaddata/lib/python3.8/site-packages/metaphlan/metaphlan_databases/mpa_v30_CHOCOPhlAn_201901
Unable to install database. Error running command: bowtie2-inspect /home/qiime2/miniconda/envs/kneaddata/lib/python3.8/site-packages/metaphlan/metaphlan_databases/mpa_v30_CHOCOPhlAn_201901 > /home/qiime2/biobakery_workflows_databases/strainphlan_db_markers/all_markers.fasta

Problem 3
If success in installation please suggest what tutorial to follow for further analysis
thanks  and regards

**Comment by kescobo** [comment]
Hi @Muneer111, it does not appear that you are using this package. Again, BiobakeryUtils.jl is a wrapper package for the julia language. I do not maintain the tools in the bioBakery. 

Please direct your questions to https://forum.biobakery.org/
