### ISSUE TITLE
Metadata import into microbial communities

### ISSUE THREAD

**Issue by kescobo** [BioJulia/BiobakeryUtils.jl#24]
Would be nice to include functionality to import a CSV file with sample metadata and allow attaching it to a `CommunityProfile` imported from metaphlan or humann.

Stretch goal - import whole thing from [BIOM file format](https://biom-format.org/).

As a proposal API, something like

```
julia> addmetadata!(comm, "some_metadata.csv")
```

Some considerations:

- How to handle samples that don't have metadata
- How to handle metadata for samples that aren't in the `comm`
- What inputs are allowed (eg probably support all Tables.jl compatible types).

Should we include output options??

**Comment by annelle-abatoni** [comment]
```
function addmetadata!(comm, “some_metadata.csv”) 
	#1 read “some_metadata.csv” and make its CommunityProfile
	Make a DataFrame 
	Make a matrix
        Make a Taxon type
        Make a Microbiome Sample type
        Make a Sparse Matrix of the Matrix 
        Make Comm using all the above	
	#retrieve the old tax and ms samples from old comm
	Not sure how to do this
	#create a newcomm with the old and new tax and ms types
```

**Comment by kescobo** [comment]
Step 1: Import `metaphlan_multi_test.tsv` as Community Profile
Step 2: Import `metadata_test.csv` as DataFrame
Step 3: add metadata from df to CP

**Comment by kescobo** [comment]
Option2, step2 detail:

1. import as dataframe
2. make vector of `MicrobiomeSample`s with sample ID column
3. for each _other_ column_ in DataFrame, `set!()` column name, value

function signature, something like

```
add_metadata!(comm::CommunityProfile, df::DataFrame, sample_name_col)
```

eg

```julia
for (i, val) in df.colname
    set!(vec_of_mss[i], colname, val)
end
```

**Comment by kescobo** [comment]
This is fixed in Microbiome end, and with `read_pcl` added in #63
