### ISSUE TITLE
What is the difference between `parsetaxon` and `findclade`?

### ISSUE THREAD

**Issue by anikaluo** [BioJulia/BiobakeryUtils.jl#39]
They look like they do the exact same thing to me. So do we actually need both functions?

**Comment by kescobo** [comment]
Why did you close? what's the answer? :laughing:

**Comment by anikaluo** [comment]
Actually, we could open this issue again. Initially I noticed that they do similar things in isolating a taxon level and then returning the clade and taxon level. The initial docs led me to believe that `parsetaxon` returned a Tuple while `findclade` returned a Taxon, so I thought that was the difference and closed the Issue. But when I was adding documentation to the functions, `parsetaxon` actually returned a Taxon, so now I do not know if there is an actual difference between the two functions.

**Comment by kescobo** [comment]
It's entirely possible that they both do the same thing, and that I wrote this functionality twice...

**Comment by kescobo** [comment]
There doesn't seem to be much of a difference:

```
julia> using BiobakeryUtils

julia> findclade("k__Archaea|p__Euryarchaeota|c__Methanobacteria", :kingdom)
Microbiome.Taxon("Archaea", :kingdom)

julia> parsetaxon("k__Archaea|p__Euryarchaeota|c__Methanobacteria", :kingdom)
Microbiome.Taxon("Archaea", :kingdom)

julia> findclade("k__Archaea|p__Euryarchaeota|c__Methanobacteria", 2)
Microbiome.Taxon("Euryarchaeota", :phylum)

julia> parsetaxon("k__Archaea|p__Euryarchaeota|c__Methanobacteria", 2)
Microbiome.Taxon("Euryarchaeota", :phylum)
```

I think I'd like to keep it as `parsetaxa` and `parsetaxon`. @annelle-abatoni I think this overlaps with #33 which you're assigned to, but @anikaluo you can tackle deduplicating if you get to it first (just mention here that you're working on it.

Just make sure that all of the methods are covered, and any usage of `findclade` in other functions are replaced. Then remove tests for `findclade` specifically.

**Comment by annelle-abatoni** [comment]
I wrote findclade when I first started before I checked what parsetaxon does, and you're totally right! We should keep parsetaxon since it has more functionality.

**Comment by anikaluo** [comment]
@annelle-abatoni are you already working on this? if not, i can take it

**Comment by anikaluo** [comment]
Oh also, if we remove `findclade` I think we can also remove `gettaxon`? `gettaxon` is not exported and only used in `findclade`.

**Comment by annelle-abatoni** [comment]
Yes, `gettaxon` was only affiliated with `findclade` so it should be fine to delete that as well. I had deleted it on my branch, but I'm having trouble merging and committing my changes, so you can go ahead and remove it on your end too.
