### ISSUE TITLE
Do we still need add_metadata! ?

### ISSUE THREAD

**Issue by annelle-abatoni** [BioJulia/BiobakeryUtils.jl#44]
I finished up `add_metadata!` using `commjoin` and `metaphlan_profile.` I don't know if we still need it though  https://github.com/BioJulia/BiobakeryUtils.jl/blob/77d475f3d884ba16a7343b968c6ef88226eb11de/src/communityprofile.jl

**Comment by kescobo** [comment]
That function doesn't actually add metadata though - metadata should be added to samples, the way this is written, it would try to make the metadata file into a community profile, and then merge it.

I think the basic function for bulk addition of metdata, taking a `CommunityProfile` and some table of metadata should be done in Microbiome.jl ([see here](https://github.com/BioJulia/Microbiome.jl/issues/63)), and I will work on that. But I think dealing with files could happen here. So for example, we could have `metaphlan_profiles()` have a keyword argument like `metadata=filename`, and then read in a CSV file with metadata, using the `Microbiome.jl` function to combine that with the `CommunityProfile`
