### ISSUE TITLE
Metaphlan: Broken Link

### ISSUE THREAD

**Issue by annelle-abatoni** [BioJulia/BiobakeryUtils.jl#54]
The metaphlan.jl code doesn't show here on this link: http://biojulia.net/BiobakeryUtils.jl/dev/metaphlan2/ , like humann2.jl and general.jl do.

**Comment by kescobo** [comment]
Yeah, all of the documentation for this package needs an overhaul. For one, should change filenames to not have the `2`s anymore, and add docstrings for all of the specific functions
